FROM nimmis/spigot

# install raspberry juice plugin
RUN wget https://github.com/zhuowei/RaspberryJuice/raw/master/jars/raspberryjuice-1.9.1.jar && \
  mkdir /minecraft/plugins && \
  mv raspberryjuice-1.9.1.jar /minecraft/plugins
